// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWB0fic1xbRe95jBEahOScEYqF4zfzSrw',
    appId: '1:989894716190:web:96cfa9f139119fa2c3f70f',
    messagingSenderId: '989894716190',
    projectId: 'chapp-99c50',
    authDomain: 'chapp-99c50.firebaseapp.com',
    storageBucket: 'chapp-99c50.firebasestorage.app',
    measurementId: 'G-0K90CKLD41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAInSCXA34i70919slru1tbhAptpGTnJe0',
    appId: '1:989894716190:android:63997a7ccf171829c3f70f',
    messagingSenderId: '989894716190',
    projectId: 'chapp-99c50',
    storageBucket: 'chapp-99c50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ5oDBY_Q76kr-dC2egOLH4nDJVMZ2qZU',
    appId: '1:989894716190:ios:fa940d4f97d5a29ec3f70f',
    messagingSenderId: '989894716190',
    projectId: 'chapp-99c50',
    storageBucket: 'chapp-99c50.firebasestorage.app',
    iosBundleId: 'com.example.chapp',
  );
}
